[ADD] Warehouse page UI
BakingUp/BakingUp-Frontend pull request #21
Opened 2024-08-25 14:21 UTC by KNattawat89

2024-08-25 14:30 UTC, KNattawat89 commented
<img width="308" alt="Screenshot 2567-08-25 at 21 29 35" src="https://github.com/user-attachments/assets/59fef2d9-9bd3-4342-862a-eb45e0022d24">
<img width="311" alt="Screenshot 2567-08-25 at 21 29 52" src="https://github.com/user-attachments/assets/d039ed59-691e-40c4-9b1b-0cc2230e8578">

2024-08-25 14:34 UTC, jedipw requested changes

2024-08-25 14:34 UTC, jedipw commented on lib/screens/add_edit_recipe_ingredient_screen.dart
แก้ไฟล์นี้ทำไมนะ?

2024-08-25 14:34 UTC, jedipw commented on lib/screens/warehouse_screen.dart
> +    // }
อันนี้น่าจะไม่ได้ใช้ อย่าลืมลบออก

2024-08-25 14:37 UTC, jedipw requested changes

2024-08-25 14:37 UTC, jedipw commented on lib/widgets/warehouse/warehouse_recipes_item.dart
> +                            ),
สีดาวเหมือนจะยังไม่ตรงกับใน UI

2024-08-25 14:44 UTC, jedipw requested changes

2024-08-25 14:44 UTC, jedipw commented on lib/screens/warehouse_screen.dart
> +                Container(
อาจจะใช้เป็น Padding แทน Container ได้

2024-08-25 15:08 UTC, jedipw requested changes

2024-08-25 15:08 UTC, jedipw commented on lib/screens/add_edit_recipe_ingredient_screen.dart
ตรงนี้ยังมีแก้ whitespace อยู่

2024-08-25 15:26 UTC, jedipw approved these changes

2024-08-25 15:32 UTC, jedipw requested changes
เวลา scroll เงาฝั่งซ้าย / ขวาหาย

2024-08-26 13:42 UTC, jedipw requested changes

2024-08-26 13:42 UTC, jedipw commented on lib/screens/add_edit_recipe_ingredient_screen.dart
> -
ตรงนี้อย่าลืมเอา whitespace กลับมา

2024-08-29 01:59 UTC, jedipw approved these changes

2024-09-01 08:14 UTC, bbbung approved these changes

2024-09-01 15:24 UTC, merged