[INTEGRATE] warehouse screen
BakingUp/BakingUp-Frontend pull request #37
Opened 2024-09-27 07:33 UTC by KNattawat89

# All feature on warehouse screen have been finished (except error page)
## Loading + Search + Filter

https://github.com/user-attachments/assets/4a2b2dca-186c-4a5f-b6e6-569b7ac46315

## Delete
### Recipe: Success
https://github.com/user-attachments/assets/aca4ab68-f6cc-49a3-afd9-49de28cf8211

### Recipe: Failed

https://github.com/user-attachments/assets/7678873d-3b10-4085-8541-ddf3c1d34078

### Ingredient: Success

https://github.com/user-attachments/assets/dce6e000-5b84-4ca4-b6e9-03aa7e8c7d52

### Ingredient: Failed

https://github.com/user-attachments/assets/465f1b37-5b4d-4331-94e0-286cde2ff03e

2024-09-27 09:10 UTC, jedipw requested changes

2024-09-27 09:10 UTC, jedipw commented on lib/models/ingredient_stock_detail.dart
แนะนำให้ rebase ก่อน เพื่อให้พวก file change ของ PR นี้หายไป [[INTEGRATE] Delete ingredient batch note ](https://github.com/BakingUp/BakingUp-Frontend/pull/36)

2024-09-27 09:10 UTC, jedipw commented on lib/models/warehouse.dart
> +class IngredietnListResponse {
Ingredietn -> Ingredient

2024-09-27 09:10 UTC, jedipw commented on lib/widgets/warehouse/warehouse_recipe/warehouse_recipes_list.dart
> +                                    widget.fetchRecipeListFunction();
หลังจากที่ delete เสร็จเรียบร้อยแล้ว คิดว่าไม่ควร fetch ใหม่ คิดว่าควรลบ recipe ออกจาก list มากกว่า

2024-09-27 09:10 UTC, jedipw commented on lib/widgets/warehouse/warehouse_ingredient/warehouse_ingredient_list.dart
> +                                    widget.fetchIngredientListFunction();
หลังจากที่ delete เสร็จเรียบร้อยแล้ว คิดว่าไม่ควร fetch ใหม่ คิดว่าควรลบ ingredient ออกจาก list มากกว่า

2024-09-27 09:10 UTC, jedipw commented on lib/widgets/baking_up_filter_modal_bottom.dart
ใช้ color จาก colors.dart แทนได้มั้ย

2024-09-27 09:10 UTC, jedipw commented on lib/widgets/baking_up_filter_modal_bottom.dart
> +              )),
ตอนนี้ setState จะใช้ได้ก็ต่อเมื่อ user กดคลิกตรง text "Filter by" / "Sort by" เท่านั้น แต่จริงๆแล้ว มันควรจะกดตรงช่องว่างๆที่อยู่ข้างๆ text ได้ด้วย

2024-09-27 09:10 UTC, jedipw commented on lib/widgets/baking_up_filter_modal_bottom.dart
เวลากดเลือก option สีที่ focus ไม่ควรทะลุแบบนี้
![Screenshot 2567-09-27 at 16 02 20](https://github.com/user-attachments/assets/d196b096-0249-42da-be3b-c9d76270b25b)

2024-09-27 09:10 UTC, jedipw commented on lib/widgets/baking_up_search_bar.dart
หลังจากที่กดคลิกตรงส่วนอื่นที่ไม่ใช่ search bar ควรจะ unfocus

2024-09-27 09:10 UTC, jedipw commented on lib/widgets/baking_up_filter_modal_bottom.dart
> +  // final List<String> filterBy = ['Stock Name', 'Quantity', 'Expiration Date'];
อันนี้น่าจะเอาออกได้

2024-09-28 10:26 UTC, bbbung approved these changes, later dismissed

2024-09-29 16:58 UTC, jedipw requested changes

2024-09-29 16:58 UTC, jedipw commented on lib/widgets/warehouse/warehouse_recipe/warehouse_recipes_list.dart
> +      barrierColor: const Color(0xC7D9D9D9),
สีตรงนี้ใช้จาก colors.dart ได้ไหม

2024-09-30 02:39 UTC, jedipw approved these changes

2024-10-03 02:00 UTC, bbbung approved these changes

2024-10-03 16:00 UTC, merged