[INTEGRATE] Stock tracking screen
BakingUp/BakingUp-Frontend pull request #38
Opened 2024-09-27 10:38 UTC by KNattawat89

# Completed feature list (except error page)
## Loading, search, and filter

https://github.com/user-attachments/assets/11759928-ca89-46e7-9169-ed45d94c7246

## Delete
### Success

https://github.com/user-attachments/assets/474d1623-1f15-4c2c-8b88-be90886e6a0c

### Failed

https://github.com/user-attachments/assets/fa73d50f-48b6-4233-9c3b-f3ae18f41c37

2024-10-04 02:50 UTC, jedipw requested changes

2024-10-04 02:50 UTC, jedipw commented on lib/screens/stock_screen.dart
> +                if (!noResult && filteredStocks.isNotEmpty)
คิดว่าถ้าเช็คแบบนี้ loading animation จะไม่ขึ้นเวลากดเข้าหน้านี้มา เพราะว่า loading animation มันอยู่ข้างใน StockList แล้วระหว่างกำลัง fetch => noResult จะยังเป็น false อยู่

2024-10-04 02:54 UTC, jedipw requested changes

2024-10-04 02:54 UTC, jedipw commented on lib/widgets/stock/stock_list.dart
> +      barrierColor: const Color(0xC7D9D9D9),
อันนี้เปลี่ยนไปใช้สีใน colors.dart

2024-10-04 02:56 UTC, jedipw requested changes

2024-10-04 02:56 UTC, jedipw commented on lib/screens/stock_detail_screen.dart
> +import 'package:bakingup_frontend/services/network_service.dart';
อันนี้น่าจะไม่ใช่ lib นะ

2024-10-04 02:56 UTC, jedipw commented on lib/screens/stock_detail_screen.dart
> +import 'package:flutter/material.dart';
lib คืออันนี้

2024-10-04 03:00 UTC, jedipw requested changes

2024-10-04 03:00 UTC, jedipw commented on lib/models/stock.dart
> +  final String lstStatus;
ควรใช้ type เป็น LSTStatus

2024-10-04 03:27 UTC, jedipw requested changes

2024-10-04 03:27 UTC, jedipw commented on lib/widgets/stock/stock_item.dart
> +                        'Selling price: ${stockList[index].sellingPrice % 1 == 0 ? stockList[index].sellingPrice.ceil() : stockList[index].sellingPrice}',
ตามที่บุ๊งบอกคือทศนิยมจะต้้งได้มากสุด 2 ตัว ไม่มีปัดขึ้น

2024-10-07 02:29 UTC, bbbung approved these changes

2024-10-07 03:54 UTC, jedipw approved these changes

2024-10-07 03:54 UTC, merged