[FIX+ADD] Deleting recipe/ingredient to zero & error handling
BakingUp/BakingUp-Frontend pull request #91
Opened 2024-11-02 13:03 UTC by KNattawat89

### delete ingredeint

https://github.com/user-attachments/assets/40563d52-0313-4876-9025-abb4aeda0597

### delete recipe

https://github.com/user-attachments/assets/e5f16f42-6adc-46cf-b220-6724c70a0f6a

### Error handling
<img width="372" alt="Screenshot 2567-11-02 at 20 02 55" src="https://github.com/user-attachments/assets/3f01dc60-33b8-4412-9381-a46d0de865fa">
<img width="373" alt="Screenshot 2567-11-02 at 20 03 01" src="https://github.com/user-attachments/assets/fc004937-ff01-4b6e-a6c9-716c94b8daa5">

2024-11-02 13:09 UTC, jedipw approved these changes, later dismissed

2024-11-02 13:49 UTC, jedipw approved these changes

2024-11-06 17:35 UTC, bbbung approved these changes

2024-11-06 17:37 UTC, bbbung requested changes
หน้า error มันต้องเป็นแบบนี้นะ 
![image](https://github.com/user-attachments/assets/ef4d73af-f87d-43f8-84a3-8b08923ba6ba)

2024-11-10 20:30 UTC, bbbung approved these changes

2024-11-10 20:31 UTC, merged